table dim_calendario
	lineageTag: c48e7203-82cc-41ac-91ef-f783ad7979f3

	column data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 05715cdc-3367-4b01-be41-b7fe25b42368
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id_data
		dataType: string
		lineageTag: 1b492fb2-9aa4-4d9c-905d-bcf027a00fd9
		summarizeBy: none
		sourceColumn: id_data

		annotation SummarizationSetBy = Automatic

	column ano
		dataType: string
		lineageTag: 4dbd0d38-2724-4424-b3fe-37325b201eba
		summarizeBy: none
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: string
		lineageTag: 42fdf459-f94a-42df-aa9e-380881bdb54d
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column dia
		dataType: string
		lineageTag: 378fb100-245e-4801-a8d8-425f12b97135
		summarizeBy: none
		sourceColumn: dia

		annotation SummarizationSetBy = Automatic

	column dia_semana_nome
		dataType: string
		lineageTag: 3f57afca-ea30-4553-bc1b-90e7c7ab411d
		summarizeBy: none
		sourceColumn: dia_semana_nome

		annotation SummarizationSetBy = Automatic

	column id_dia_semana
		dataType: string
		lineageTag: 794093c3-9e75-4e87-b8b8-daef08ed928a
		summarizeBy: none
		sourceColumn: id_dia_semana

		annotation SummarizationSetBy = Automatic

	column estacao_ano
		dataType: string
		lineageTag: a40ec653-f7c4-4ba5-947d-8d5371201b2e
		summarizeBy: none
		sourceColumn: estacao_ano

		annotation SummarizationSetBy = Automatic

	partition dim_calendario = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Legião\Projeto Waves\data\gold\tabelas_dimensionais\dim_calendario.csv"),[Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"data", type date}, {"id_data", type text}, {"ano", type text}, {"mes", type text}, {"dia", type text}, {"dia_semana_nome", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "id_dia_semana", each if [dia_semana_nome] = "Segunda-feira" then 0 else if [dia_semana_nome] = "Terça-feira" then 1 else if [dia_semana_nome] = "Quarta-feira" then 2 else if [dia_semana_nome] = "Quinta-feira" then 3 else if [dia_semana_nome] = "Sexta-feira" then 4 else if [dia_semana_nome] = "Sábado" then 5 else if [dia_semana_nome] = "Domingo" then 6 else null, type number),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"id_dia_semana", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

